import { supabaseAdmin, isSupabaseConfigured } from "@/lib/supabase";

export interface EWasteListing {
  id: string;
  deviceName: string;
  brand: string;
  category: string;
  condition: string;
  estimatedAge: string;
  description: string;
  imageUrl: string;
  price: string;
  weightKg: number;
  sellerName: string;
  sellerCity: string;
  sellerPhone?: string;
  sellerEmail?: string;
  sellerWhatsapp?: string;
  sellerAddress?: string;
  sellerState?: string;
  sellerPincode?: string;
  latitude?: string;
  longitude?: string;
  sellerRole: string;
  status: "AVAILABLE" | "BID_RECEIVED" | "SOLD" | "GOV_RESERVED";
  createdAt: string;
}

// In-memory store persistent during node process lifecycle
const globalEWaste = globalThis as unknown as {
  ewasteStore?: EWasteListing[];
};

if (!globalEWaste.ewasteStore) {
  globalEWaste.ewasteStore = [
    {
      id: "ew_101",
      deviceName: "HP Pavilion g6 Laptop Scrap (Screen & Hinge Broken)",
      brand: "HP",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "Motherboard fault. Screen panel removed, broken hinges, missing keys, exposed circuit board. Good for scrap metal & part extraction.",
      imageUrl: "/images/scrap/hp_laptop_scrap.png",
      price: "₹1,800",
      weightKg: 2.4,
      sellerName: "Rajesh Kumar",
      sellerCity: "New Delhi",
      sellerPhone: "9876543210",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T10:30:00Z",
    },
    {
      id: "ew_102",
      deviceName: "Samsung Galaxy S10 Plus (Shattered Screen Scrap)",
      brand: "Samsung",
      category: "Mobile Phones & Tablets",
      condition: "Partially Working",
      estimatedAge: "3 years",
      description: "Shattered screen display, back glass removed, exposed motherboard & battery slot. High gold/copper scrap recovery.",
      imageUrl: "/images/scrap/samsung_phone_scrap.png",
      price: "₹950",
      weightKg: 0.18,
      sellerName: "Anbu Chezhian",
      sellerCity: "Salem",
      sellerPhone: "9876543211",
      sellerAddress: "Five Roads Junction, Salem",
      sellerState: "Tamil Nadu",
      sellerPincode: "636004",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T11:15:00Z",
    },
    {
      id: "ew_103",
      deviceName: "LG Refrigerator Heavy Scrap (Copper Coil & Motor)",
      brand: "LG",
      category: "Refrigerators & ACs",
      condition: "Non-working / Damaged",
      estimatedAge: "7 years",
      description: "Heavy rust, dented metal frame, broken handle, removed compressor, exposed copper coils. Heavy metal recycling candidate.",
      imageUrl: "/images/scrap/refrigerator_scrap.png",
      price: "₹3,500",
      weightKg: 52.0,
      sellerName: "Priya Sharma",
      sellerCity: "Bengaluru",
      sellerPhone: "9876543212",
      sellerAddress: "Peenya Industrial Area Phase 2",
      sellerState: "Karnataka",
      sellerPincode: "560058",
      sellerRole: "Citizen",
      status: "GOV_RESERVED",
      createdAt: "2026-07-31T12:00:00Z",
    },
    {
      id: "ew_104",
      deviceName: "50 kg Pure Heavy Copper Winding Wire Scrap",
      brand: "Industrial Copper",
      category: "Batteries & Cables",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "5 years",
      description: "50 kg bundle of heavy copper motor & transformer winding wire scrap. High purity electrical copper for recycling melting.",
      imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
      price: "₹28,500",
      weightKg: 50.0,
      sellerName: "Karthick A.",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543213",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T13:00:00Z",
    },
    {
      id: "ew_105",
      deviceName: "Broken CPU Desktop Towers Scrap Lot (Bundle of 10)",
      brand: "Mixed (Dell/HP/Lenovo)",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "6 years",
      description: "10 numbers old burnt CPU cabinets. Includes motherboard, power supply, heatsinks, steel cases and wiring.",
      imageUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&auto=format&fit=crop&q=80",
      price: "₹5,200",
      weightKg: 42.0,
      sellerName: "Senthil Kumar",
      sellerCity: "Chennai",
      sellerPhone: "9876543214",
      sellerAddress: "Guindy Industrial Estate, Chennai",
      sellerState: "Tamil Nadu",
      sellerPincode: "600032",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T13:30:00Z",
    },
    {
      id: "ew_106",
      deviceName: "Broken Optical Mouse Scrap Bundle (40 Pieces)",
      brand: "Logitech / HP / Dell",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "3 years",
      description: "40 numbers broken wired USB optical mice. Cut cables, faulty sensors, plastic body and small PCB scrap.",
      imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80",
      price: "₹1,200",
      weightKg: 4.5,
      sellerName: "Mani Vannan",
      sellerCity: "Madurai",
      sellerPhone: "9876543215",
      sellerAddress: "KK Nagar, Madurai",
      sellerState: "Tamil Nadu",
      sellerPincode: "625020",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T14:00:00Z",
    },
    {
      id: "ew_107",
      deviceName: "Broken CRT Glass Monitor Scrap Lot (4 Units)",
      brand: "LG / Samsung",
      category: "TVs & Monitors",
      condition: "Non-working / Damaged",
      estimatedAge: "12 years",
      description: "Heavy old CRT glass monitors for scrap metal, copper yoke coil and glass tube recycling. Very heavy units.",
      imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
      price: "₹2,100",
      weightKg: 58.0,
      sellerName: "Ramesh Babu",
      sellerCity: "Trichy",
      sellerPhone: "9876543216",
      sellerAddress: "Thillai Nagar, Trichy",
      sellerState: "Tamil Nadu",
      sellerPincode: "620018",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T14:15:00Z",
    },
    {
      id: "ew_108",
      deviceName: "High-Grade Motherboard PCB Board Scrap (15 kg)",
      brand: "Asus / Gigabyte / Intel",
      category: "Laptops & Computers",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "5 years",
      description: "15 kg mix of green & blue computer motherboards. High yield precious metals (gold pins, IC chips, copper tracks).",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80",
      price: "₹8,400",
      weightKg: 15.0,
      sellerName: "Venkatesh R.",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543217",
      sellerAddress: "Gandhipuram, Coimbatore",
      sellerState: "Tamil Nadu",
      sellerPincode: "641012",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T14:30:00Z",
    },
    {
      id: "ew_109",
      deviceName: "Scrap Lead-Acid Inverter Battery 150Ah (Heavy Lead)",
      brand: "Exide / Luminous",
      category: "Batteries & Cables",
      condition: "Non-working / Damaged",
      estimatedAge: "5 years",
      description: "Dead 150Ah inverter battery. Heavy lead plates and plastic casing. Intact lead recovery candidate.",
      imageUrl: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
      price: "₹4,200",
      weightKg: 42.0,
      sellerName: "Deepak Verma",
      sellerCity: "New Delhi",
      sellerPhone: "9876543218",
      sellerAddress: "Okhla Industrial Area Phase 3",
      sellerState: "Delhi",
      sellerPincode: "110020",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T14:45:00Z",
    },
    {
      id: "ew_110",
      deviceName: "Old Mechanical & USB Keyboard Scrap Lot (25 Pcs)",
      brand: "TVS Gold / Dell / HP",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "25 numbers broken computer keyboards. Missing keys, damaged key switches, copper wire cords.",
      imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
      price: "₹1,650",
      weightKg: 18.0,
      sellerName: "Gokul Nath",
      sellerCity: "Erode",
      sellerPhone: "9876543219",
      sellerAddress: "Bhavani Road, Erode",
      sellerState: "Tamil Nadu",
      sellerPincode: "638004",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T15:00:00Z",
    },
    {
      id: "ew_111",
      deviceName: "Dead Split AC Outdoor Unit Scrap with Compressor (35 kg)",
      brand: "Voltas / Blue Star",
      category: "Refrigerators & ACs",
      condition: "Non-working / Damaged",
      estimatedAge: "6 years",
      description: "Seized compressor, copper coil radiator fins, steel body casing and fan motor.",
      imageUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
      price: "₹6,800",
      weightKg: 35.0,
      sellerName: "Saravanan T.",
      sellerCity: "Salem",
      sellerPhone: "9876543220",
      sellerAddress: "Fairlands, Salem",
      sellerState: "Tamil Nadu",
      sellerPincode: "636016",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T15:15:00Z",
    },
    {
      id: "ew_112",
      deviceName: "Stripped Copper Cable Wire Bundle (20 kg)",
      brand: "Electrical Cables",
      category: "Batteries & Cables",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "3 years",
      description: "20 kg heavy copper wire strands stripped from old industrial equipment and power lines.",
      imageUrl: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&auto=format&fit=crop&q=80",
      price: "₹11,400",
      weightKg: 20.0,
      sellerName: "Vijay Anand",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543221",
      sellerAddress: "Peelamedu, Coimbatore",
      sellerState: "Tamil Nadu",
      sellerPincode: "641004",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T15:30:00Z",
    },
    {
      id: "ew_113",
      deviceName: "Dead Smart Phones & Feature Phone Scrap Lot (50 Pcs)",
      brand: "Nokia / Samsung / Mi",
      category: "Mobile Phones & Tablets",
      condition: "Non-working / Damaged",
      estimatedAge: "5 years",
      description: "50 numbers dead mobile handsets. Water damaged, cracked screens, board scrap for gold and tantalum refining.",
      imageUrl: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&q=80",
      price: "₹5,400",
      weightKg: 6.5,
      sellerName: "Arun Kumar",
      sellerCity: "Chennai",
      sellerPhone: "9876543222",
      sellerAddress: "T Nagar, Chennai",
      sellerState: "Tamil Nadu",
      sellerPincode: "600017",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T15:45:00Z",
    },
    {
      id: "ew_114",
      deviceName: "Burnt Washing Machine Motor & Copper Coil Scrap",
      brand: "Whirlpool",
      category: "Washing Machines",
      condition: "Non-working / Damaged",
      estimatedAge: "8 years",
      description: "Burnt electric motor, copper winding, iron rotor and belt pulley assembly.",
      imageUrl: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=600&auto=format&fit=crop&q=80",
      price: "₹1,950",
      weightKg: 12.5,
      sellerName: "Lakshmi Narayanan",
      sellerCity: "Tiruppur",
      sellerPhone: "9876543223",
      sellerAddress: "Avinashi Road, Tiruppur",
      sellerState: "Tamil Nadu",
      sellerPincode: "641602",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T16:00:00Z",
    },
    {
      id: "ew_115",
      deviceName: "Gold Finger RAM Memory Card Scrap (2 kg)",
      brand: "Kingston / Hynix / Samsung",
      category: "Laptops & Computers",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "6 years",
      description: "2 kg DDR2 / DDR3 RAM stick boards with gold contacts. Premium e-waste refining material.",
      imageUrl: "https://images.unsplash.com/photo-1562976540-1502c2145186?w=600&auto=format&fit=crop&q=80",
      price: "₹8,900",
      weightKg: 2.0,
      sellerName: "Siddharth Jain",
      sellerCity: "Bengaluru",
      sellerPhone: "9876543224",
      sellerAddress: "Electronic City Phase 1",
      sellerState: "Karnataka",
      sellerPincode: "560100",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T16:15:00Z",
    },
    {
      id: "ew_116",
      deviceName: "Damaged SMPS Power Supply Units Scrap Lot (15 Pcs)",
      brand: "Corsair / Circle / Artis",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "15 numbers burnt PC power supplies containing transformers, aluminum heat sinks, copper coils, and cooling fans.",
      imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600&auto=format&fit=crop&q=80",
      price: "₹2,800",
      weightKg: 22.0,
      sellerName: "Pradeep Raj",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543225",
      sellerAddress: "Singanallur, Coimbatore",
      sellerState: "Tamil Nadu",
      sellerPincode: "641005",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T16:30:00Z",
    },
    {
      id: "ew_117",
      deviceName: "Industrial Heavy Xerox Copier Machine Scrap (65 kg)",
      brand: "Canon / Ricoh",
      category: "Printers & Scanners",
      condition: "Non-working / Damaged",
      estimatedAge: "9 years",
      description: "Non-functional commercial office copier. Steel frame, motors, gears, optical glass scanner and electronic boards.",
      imageUrl: "https://images.unsplash.com/photo-1612815150366-a813625b414f?w=600&auto=format&fit=crop&q=80",
      price: "₹7,800",
      weightKg: 65.0,
      sellerName: "Balaji K.",
      sellerCity: "Chennai",
      sellerPhone: "9876543226",
      sellerAddress: "Ambattur Industrial Estate",
      sellerState: "Tamil Nadu",
      sellerPincode: "600058",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T16:45:00Z",
    },
    {
      id: "ew_118",
      deviceName: "Swollen Lithium-Ion Laptop Battery Scrap (30 Pcs)",
      brand: "Dell / Lenovo / HP",
      category: "Batteries & Cables",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "30 numbers dead laptop battery packs. Cobalt, nickel, lithium element recycling candidate.",
      imageUrl: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
      price: "₹3,200",
      weightKg: 9.0,
      sellerName: "Kannan M.",
      sellerCity: "Madurai",
      sellerPhone: "9876543227",
      sellerAddress: "Anna Nagar, Madurai",
      sellerState: "Tamil Nadu",
      sellerPincode: "625020",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T17:00:00Z",
    },
    {
      id: "ew_119",
      deviceName: "Old Server Chassis & Server Board Scrap (38 kg)",
      brand: "HP ProLiant / IBM",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "7 years",
      description: "38 kg dual-socket server motherboard, redundant power modules, SAS backplane, aluminum heatsinks and heavy steel rack case.",
      imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
      price: "₹9,500",
      weightKg: 38.0,
      sellerName: "Naveen Pattanaik",
      sellerCity: "Hyderabad",
      sellerPhone: "9876543228",
      sellerAddress: "HITEC City, Hyderabad",
      sellerState: "Telangana",
      sellerPincode: "500081",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T17:15:00Z",
    },
    {
      id: "ew_120",
      deviceName: "Broken Laserjet Printer Scrap Lot (3 Units)",
      brand: "HP LaserJet",
      category: "Printers & Scanners",
      condition: "Non-working / Damaged",
      estimatedAge: "5 years",
      description: "3 numbers broken monochrome laser printers. Fuser assembly fault, stepper motors, circuit boards and copper transformer.",
      imageUrl: "https://images.unsplash.com/photo-1612815150366-a813625b414f?w=600&auto=format&fit=crop&q=80",
      price: "₹2,100",
      weightKg: 21.0,
      sellerName: "Ragu Vamsi",
      sellerCity: "Vijayawada",
      sellerPhone: "9876543229",
      sellerAddress: "Auto Nagar, Vijayawada",
      sellerState: "Andhra Pradesh",
      sellerPincode: "520007",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T17:30:00Z",
    },
    {
      id: "ew_121",
      deviceName: "Ceiling Fan & Water Pump Motor Scrap Bundle (25 kg)",
      brand: "Crompton / Orient",
      category: "Home Appliances",
      condition: "Non-working / Damaged",
      estimatedAge: "8 years",
      description: "25 kg burnt fan stator coils, monoblock pump copper winding, iron core and bearings.",
      imageUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
      price: "₹3,400",
      weightKg: 25.0,
      sellerName: "Senthil Nathan",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543230",
      sellerAddress: "Uthanapalayam, Coimbatore",
      sellerState: "Tamil Nadu",
      sellerPincode: "641028",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T17:45:00Z",
    },
    {
      id: "ew_122",
      deviceName: "Mixed VGA, HDMI, Power Cord & Adapter Scrap (30 kg)",
      brand: "Assorted Copper Cables",
      category: "Batteries & Cables",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "4 years",
      description: "30 kg box of mixed computer power cords, laptop charger adapters, VGA/DVI cables and ethernet patch wires.",
      imageUrl: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&auto=format&fit=crop&q=80",
      price: "₹4,100",
      weightKg: 30.0,
      sellerName: "Manohar Lal",
      sellerCity: "Pune",
      sellerPhone: "9876543231",
      sellerAddress: "Pimpri Chinchwad, Pune",
      sellerState: "Maharashtra",
      sellerPincode: "411018",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T18:00:00Z",
    },
    {
      id: "ew_123",
      deviceName: "Old Microwave Oven Scrap with Heavy Magnetron",
      brand: "IFB / Samsung",
      category: "Home Appliances",
      condition: "Non-working / Damaged",
      estimatedAge: "6 years",
      description: "Dead microwave oven containing high-voltage copper transformer, magnetron tube, door interlock switches, and sheet steel.",
      imageUrl: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80",
      price: "₹1,450",
      weightKg: 14.0,
      sellerName: "Sanjay Gupta",
      sellerCity: "Kanpur",
      sellerPhone: "9876543232",
      sellerAddress: "Panki Industrial Area, Kanpur",
      sellerState: "Uttar Pradesh",
      sellerPincode: "208022",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T18:15:00Z",
    },
    {
      id: "ew_124",
      deviceName: "Scrap Intel Core / Pentium Processors (50 Pcs)",
      brand: "Intel / AMD",
      category: "Laptops & Computers",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "8 years",
      description: "50 numbers old LGA775 / Socket 1155 CPU chips. Gold pins and cap metal recovery candidate.",
      imageUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&auto=format&fit=crop&q=80",
      price: "₹6,400",
      weightKg: 2.2,
      sellerName: "Abhinav Sharma",
      sellerCity: "Jaipur",
      sellerPhone: "9876543233",
      sellerAddress: "VKIA Industrial Area, Jaipur",
      sellerState: "Rajasthan",
      sellerPincode: "302013",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T18:30:00Z",
    },
    {
      id: "ew_125",
      deviceName: "Mixed Telecom Equipment & Modem Board Scrap (20 kg)",
      brand: "Cisco / Huawei / D-Link",
      category: "Laptops & Computers",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "6 years",
      description: "20 kg telecom router boards, ADSL modems, network switches. High density IC chips and gold contacts.",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80",
      price: "₹9,800",
      weightKg: 20.0,
      sellerName: "Nitin Gadkari",
      sellerCity: "Nagpur",
      sellerPhone: "9876543234",
      sellerAddress: "MIDC Hingna, Nagpur",
      sellerState: "Maharashtra",
      sellerPincode: "440016",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T18:45:00Z",
    },
    {
      id: "ew_126",
      deviceName: "Cracked LCD/LED Monitor Display Panel Scrap (6 Pcs)",
      brand: "Dell / BenQ / Acer",
      category: "TVs & Monitors",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "6 numbers broken 19.5-inch & 21.5-inch LED monitor panels. CCFL backlight, driver boards and aluminum frame.",
      imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80",
      price: "₹2,600",
      weightKg: 24.0,
      sellerName: "Gopal Krishna",
      sellerCity: "Salem",
      sellerPhone: "9876543235",
      sellerAddress: "Meyyanur, Salem",
      sellerState: "Tamil Nadu",
      sellerPincode: "636004",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T19:00:00Z",
    },
    {
      id: "ew_127",
      deviceName: "Smashed Android Tablet Scrap Lot (10 Pcs)",
      brand: "Lenovo / iBall / Micromax",
      category: "Mobile Phones & Tablets",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "10 numbers dead tablets. Shattered glass, swollen batteries, motherboard scrap.",
      imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80",
      price: "₹3,100",
      weightKg: 4.8,
      sellerName: "Mohd Imran",
      sellerCity: "Lucknow",
      sellerPhone: "9876543236",
      sellerAddress: "Hazratganj, Lucknow",
      sellerState: "Uttar Pradesh",
      sellerPincode: "226001",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T19:15:00Z",
    },
    {
      id: "ew_128",
      deviceName: "Old UPS Lead-Acid Batteries Scrap Lot (8 Pcs)",
      brand: "APC / Microtek 12V 7Ah",
      category: "Batteries & Cables",
      condition: "Non-working / Damaged",
      estimatedAge: "3 years",
      description: "8 numbers dead 12V 7Ah sealed lead-acid batteries from computer UPS backups.",
      imageUrl: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
      price: "₹3,800",
      weightKg: 19.5,
      sellerName: "Dinesh Kumar",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543237",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T19:30:00Z",
    },
    {
      id: "ew_129",
      deviceName: "Industrial Transformer Scrap with Heavy Copper Coils (45 kg)",
      brand: "Kirloskar",
      category: "Batteries & Cables",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "10 years",
      description: "45 kg heavy step-down industrial transformer. Thick copper wire coils and laminated silicon steel core.",
      imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
      price: "₹24,500",
      weightKg: 45.0,
      sellerName: "Murugan P.",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543238",
      sellerAddress: "Sidco Industrial Estate, Kurichi",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T19:45:00Z",
    },
    {
      id: "ew_130",
      deviceName: "Aluminum Heat Sink Scrap Bundle (18 kg)",
      brand: "Cooler Master / Intel",
      category: "Laptops & Computers",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "5 years",
      description: "18 kg extrusion aluminum heatsinks from computer motherboards, graphics cards, and power supplies.",
      imageUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&auto=format&fit=crop&q=80",
      price: "₹3,200",
      weightKg: 18.0,
      sellerName: "Kishore Kumar",
      sellerCity: "Chennai",
      sellerPhone: "9876543239",
      sellerAddress: "Chromepet, Chennai",
      sellerState: "Tamil Nadu",
      sellerPincode: "600044",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T20:00:00Z",
    },
    {
      id: "ew_131",
      deviceName: "Old CRT Television Scrap (32-inch Heavy Unit)",
      brand: "Onida / BPL",
      category: "TVs & Monitors",
      condition: "Non-working / Damaged",
      estimatedAge: "15 years",
      description: "Vintage 32-inch CRT television set. Thick copper yoke coil, heavy glass tube, speaker magnets and steel chassis.",
      imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
      price: "₹1,250",
      weightKg: 34.0,
      sellerName: "Palanisamy K.",
      sellerCity: "Pollachi",
      sellerPhone: "9876543240",
      sellerAddress: "New Scheme Road, Pollachi",
      sellerState: "Tamil Nadu",
      sellerPincode: "642001",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T20:15:00Z",
    },
    {
      id: "ew_132",
      deviceName: "Broken Hard Disk Drive Scrap Lot (12 Pcs)",
      brand: "Seagate / Western Digital 3.5\"",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "6 years",
      description: "12 numbers 3.5-inch desktop hard drives. Contains neodymium magnets, aluminum platters, and PCB boards.",
      imageUrl: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80",
      price: "₹2,400",
      weightKg: 7.2,
      sellerName: "Rajeev Menon",
      sellerCity: "Kochi",
      sellerPhone: "9876543241",
      sellerAddress: "Kaloor, Kochi",
      sellerState: "Kerala",
      sellerPincode: "682017",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T20:30:00Z",
    },
    {
      id: "ew_133",
      deviceName: "Scrap Copper Motors from AC & Refrigerator (4 Pcs)",
      brand: "Godrej / Voltas",
      category: "Refrigerators & ACs",
      condition: "Non-working / Damaged",
      estimatedAge: "7 years",
      description: "4 numbers dead sealed compressor motors. Heavy copper coil winding, cast iron housing.",
      imageUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
      price: "₹5,600",
      weightKg: 44.0,
      sellerName: "Velusamy T.",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543242",
      sellerAddress: "Mettupalayam Road, Coimbatore",
      sellerState: "Tamil Nadu",
      sellerPincode: "641043",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T20:45:00Z",
    },
    {
      id: "ew_134",
      deviceName: "Burnt CCTV DVR & Security Camera Scrap Lot (8 Pcs)",
      brand: "CP Plus / Hikvision",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "1 number 16-channel DVR box with burnt motherboard + 7 numbers dome and bullet cameras.",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80",
      price: "₹2,900",
      weightKg: 9.5,
      sellerName: "Subash Chandra",
      sellerCity: "Kolkata",
      sellerPhone: "9876543243",
      sellerAddress: "Salt Lake Sector 5, Kolkata",
      sellerState: "West Bengal",
      sellerPincode: "700091",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:00:00Z",
    },
    {
      id: "ew_135",
      deviceName: "Old Feature Phones Scrap Lot (30 Pcs)",
      brand: "Nokia 1100 / Samsung Guru",
      category: "Mobile Phones & Tablets",
      condition: "Non-working / Damaged",
      estimatedAge: "10 years",
      description: "30 numbers keypad mobile phones. Rich in gold plating on keypad contacts and PCB motherboards.",
      imageUrl: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&q=80",
      price: "₹1,950",
      weightKg: 3.2,
      sellerName: "Thangavelu K.",
      sellerCity: "Karur",
      sellerPhone: "9876543244",
      sellerAddress: "Textile Coastal Road, Karur",
      sellerState: "Tamil Nadu",
      sellerPincode: "639001",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:15:00Z",
    },
    {
      id: "ew_136",
      deviceName: "Damaged Samsung 32-inch LED TV Screen Scrap",
      brand: "Samsung LED TV",
      category: "TVs & Monitors",
      condition: "Non-working / Damaged",
      estimatedAge: "5 years",
      description: "Lightening damaged 32-inch LED TV. Cracked screen glass, power supply board, motherboard, and speakers intact.",
      imageUrl: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80",
      price: "₹1,750",
      weightKg: 7.5,
      sellerName: "Aravind Swamy",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543245",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:30:00Z",
    },
    {
      id: "ew_137",
      deviceName: "Scrap Graphics Card GPU Boards Lot (5 Pcs)",
      brand: "Nvidia GeForce / AMD Radeon",
      category: "Laptops & Computers",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "6 years",
      description: "5 numbers burnt GPU video cards (GTX 750Ti/960). High gold edge connector yield and copper heat pipes.",
      imageUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&auto=format&fit=crop&q=80",
      price: "₹4,800",
      weightKg: 3.5,
      sellerName: "Karthik Raja",
      sellerCity: "Chennai",
      sellerPhone: "9876543246",
      sellerAddress: "Velachery, Chennai",
      sellerState: "Tamil Nadu",
      sellerPincode: "600042",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:40:00Z",
    },
    {
      id: "ew_138",
      deviceName: "35 kg Industrial Copper Coil & Motor Winding Scrap",
      brand: "Electrical Motors",
      category: "Batteries & Cables",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "6 years",
      description: "35 kg heavy copper wire coils recovered from industrial induction motors and generators.",
      imageUrl: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&auto=format&fit=crop&q=80",
      price: "₹19,800",
      weightKg: 35.0,
      sellerName: "Sundaramurthy",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543247",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:45:00Z",
    },
    {
      id: "ew_139",
      deviceName: "Broken CRT Television Deflection Yoke Copper Coil Scrap",
      brand: "Bharat Electronics",
      category: "TVs & Monitors",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "12 years",
      description: "Copper yoke winding coils extracted from old 21-inch CRT televisions (15 kg lot). Very pure magnet wire copper.",
      imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
      price: "₹8,200",
      weightKg: 15.0,
      sellerName: "Dhanasekar M.",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543248",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:46:00Z",
    },
    {
      id: "ew_140",
      deviceName: "Old CRT Computer Monitor Wire & Glass Tube Scrap (10 Pcs)",
      brand: "Samsung SyncMaster / LG",
      category: "TVs & Monitors",
      condition: "Non-working / Damaged",
      estimatedAge: "14 years",
      description: "10 numbers heavy old CRT monitors. Glass CRT tube, copper yoke coil, steel frame and power board.",
      imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
      price: "₹4,500",
      weightKg: 110.0,
      sellerName: "Praveen Raj",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543249",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:47:00Z",
    },
    {
      id: "ew_141",
      deviceName: "Burnt CPU Cooling Fans & Heatsink Scrap Bundle (40 Pcs)",
      brand: "Intel / AMD Original",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "5 years",
      description: "40 numbers desktop CPU coolers. Copper core center, aluminum fin radiator, brushless motor.",
      imageUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&auto=format&fit=crop&q=80",
      price: "₹2,400",
      weightKg: 14.0,
      sellerName: "Vimal Kumar",
      sellerCity: "Salem",
      sellerPhone: "9876543250",
      sellerAddress: "Suramangalam, Salem",
      sellerState: "Tamil Nadu",
      sellerPincode: "636005",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:48:00Z",
    },
    {
      id: "ew_142",
      deviceName: "Old Landline & Cordless Telephone Scrap Bundle (20 Pcs)",
      brand: "Beetel / Panasonic",
      category: "Other Electronics",
      condition: "Non-working / Damaged",
      estimatedAge: "10 years",
      description: "20 numbers vintage landline telephone instruments. Circuit boards, copper cords, earpiece magnet speaker.",
      imageUrl: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&q=80",
      price: "₹1,400",
      weightKg: 11.0,
      sellerName: "Chidambaram N.",
      sellerCity: "Madurai",
      sellerPhone: "9876543251",
      sellerAddress: "Simmakkal, Madurai",
      sellerState: "Tamil Nadu",
      sellerPincode: "625001",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:49:00Z",
    },
    {
      id: "ew_143",
      deviceName: "Broken Laptop Screen LED Panel Scrap (15 Pcs)",
      brand: "AU Optronics / LG Display",
      category: "Laptops & Computers",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "15 numbers cracked 14-inch & 15.6-inch laptop screens. Driver PCB board, LED backlight strip, thin glass layer.",
      imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80",
      price: "₹2,200",
      weightKg: 6.5,
      sellerName: "Niranjan Swamy",
      sellerCity: "Erode",
      sellerPhone: "9876543252",
      sellerAddress: "Perundurai Road, Erode",
      sellerState: "Tamil Nadu",
      sellerPincode: "638011",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:50:00Z",
    },
    {
      id: "ew_144",
      deviceName: "Burnt Subwoofer & Speaker Magnet Scrap Lot (8 Pcs)",
      brand: "Creative / Sony",
      category: "Home Appliances",
      condition: "Non-working / Damaged",
      estimatedAge: "6 years",
      description: "8 numbers burnt audio speakers & subwoofer drivers. Heavy ferrite magnet ring, voice coil copper wire.",
      imageUrl: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
      price: "₹1,850",
      weightKg: 16.0,
      sellerName: "Hariharan V.",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543253",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:51:00Z",
    },
    {
      id: "ew_145",
      deviceName: "Industrial 3-Phase Electric Motor Copper Scrap (40 kg)",
      brand: "Siemens / ABB",
      category: "Home Appliances",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "9 years",
      description: "40 kg heavy industrial 3-phase induction motor scrap. Pure copper stator winding, cast iron frame, heavy rotor.",
      imageUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
      price: "₹21,500",
      weightKg: 40.0,
      sellerName: "Anguharikarthick",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543254",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:52:00Z",
    },
    {
      id: "ew_146",
      deviceName: "Damaged Inkjet Printer Cartridge & Circuit Board Scrap (20 Pcs)",
      brand: "HP / Canon DeskJet",
      category: "Printers & Scanners",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "20 numbers broken color and black printers. Small stepper motors, copper wire harness, power adapter, logic board.",
      imageUrl: "https://images.unsplash.com/photo-1612815150366-a813625b414f?w=600&auto=format&fit=crop&q=80",
      price: "₹2,600",
      weightKg: 32.0,
      sellerName: "Senthil Kumar",
      sellerCity: "Trichy",
      sellerPhone: "9876543255",
      sellerAddress: "Cantonment, Trichy",
      sellerState: "Tamil Nadu",
      sellerPincode: "620001",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:53:00Z",
    },
    {
      id: "ew_147",
      deviceName: "Old Car Lead-Acid Battery Scrap 35Ah (Heavy Lead)",
      brand: "Amaron / Exide",
      category: "Batteries & Cables",
      condition: "Non-working / Damaged",
      estimatedAge: "4 years",
      description: "Dead 12V 35Ah automotive battery. Intact lead plates and heavy plastic casing.",
      imageUrl: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
      price: "₹2,450",
      weightKg: 11.5,
      sellerName: "Manikandan R.",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543256",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:54:00Z",
    },
    {
      id: "ew_148",
      deviceName: "Burnt Solar Inverter Circuit Board Scrap (12 kg)",
      brand: "Microtek / Sukam",
      category: "Batteries & Cables",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "5 years",
      description: "12 kg heavy solar inverter PCB boards with MOSFET transistors, copper transformers, heat sinks, and capacitors.",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80",
      price: "₹6,800",
      weightKg: 12.0,
      sellerName: "Vijay Kumar",
      sellerCity: "Salem",
      sellerPhone: "9876543257",
      sellerAddress: "Attur, Salem",
      sellerState: "Tamil Nadu",
      sellerPincode: "636102",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:55:00Z",
    },
    {
      id: "ew_149",
      deviceName: "Damaged Stabilizer Transformer & Copper Wire Scrap (18 kg)",
      brand: "V-Guard",
      category: "Batteries & Cables",
      condition: "Non-working / Damaged",
      estimatedAge: "6 years",
      description: "18 kg heavy voltage stabilizer scrap. Heavy copper toroidal transformer coil, relay switches, steel housing.",
      imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
      price: "₹9,200",
      weightKg: 18.0,
      sellerName: "Anguharikarthick",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543258",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:56:00Z",
    },
    {
      id: "ew_150",
      deviceName: "High-Grade Gold Pin Server CPU Processor Scrap (20 Pcs)",
      brand: "Intel Xeon / AMD EPYC",
      category: "Laptops & Computers",
      condition: "Scrap for Parts & Metals",
      estimatedAge: "7 years",
      description: "20 numbers LGA2011 server processors. Gold plated contact pins, heavy metal heat spreader, premium refining lot.",
      imageUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&auto=format&fit=crop&q=80",
      price: "₹12,500",
      weightKg: 1.8,
      sellerName: "Anguharikarthick",
      sellerCity: "Coimbatore",
      sellerPhone: "9876543259",
      sellerAddress: "Rathinam Technical Campus, Eachanari",
      sellerState: "Tamil Nadu",
      sellerPincode: "641021",
      sellerRole: "Citizen",
      status: "AVAILABLE",
      createdAt: "2026-07-31T21:57:00Z",
    },
  ];
}

export const ewasteStore = globalEWaste.ewasteStore;

export async function getEWasteListingsAsync(): Promise<EWasteListing[]> {
  // Always start with local seed store (50+ items)
  const localItems = [...(globalEWaste.ewasteStore || [])];

  if (isSupabaseConfigured()) {
    try {
      const { data, error } = await supabaseAdmin
        .from("ewaste_listings")
        .select("*")
        .order("created_at", { ascending: false });

      if (data && !error && data.length > 0) {
        const supabaseItems: EWasteListing[] = data.map((item: any) => ({
          id: item.id,
          deviceName: item.device_name,
          brand: item.brand || "Generic",
          category: item.category,
          condition: item.condition,
          estimatedAge: item.estimated_age || "3 years",
          description: item.description || "",
          imageUrl: item.image_url,
          price: item.price,
          weightKg: Number(item.weight_kg) || 2.5,
          sellerName: item.seller_name,
          sellerCity: item.seller_city,
          sellerPhone: item.seller_phone,
          sellerEmail: item.seller_email,
          sellerWhatsapp: item.seller_whatsapp,
          sellerAddress: item.seller_address,
          sellerState: item.seller_state,
          sellerPincode: item.seller_pincode,
          latitude: item.latitude,
          longitude: item.longitude,
          sellerRole: item.seller_role || "Citizen",
          status: item.status || "AVAILABLE",
          createdAt: item.created_at,
        }));
        // Merge: Supabase items first (newest), then local seed items not already in Supabase
        const supabaseIds = new Set(supabaseItems.map((i) => i.id));
        const uniqueLocal = localItems.filter((i) => !supabaseIds.has(i.id));
        return [...supabaseItems, ...uniqueLocal];
      }
    } catch (e) {
      console.warn("Supabase fetch error, fallback to local store:", e);
    }
  }

  return localItems;
}

export function getEWasteListings(): EWasteListing[] {
  return [...(globalEWaste.ewasteStore || [])];
}

export async function addEWasteListingAsync(item: Omit<EWasteListing, "id" | "createdAt" | "status">): Promise<EWasteListing> {
  const newListing: EWasteListing = {
    ...item,
    id: `ew_${Date.now()}`,
    status: "AVAILABLE",
    createdAt: new Date().toISOString(),
  };

  if (!globalEWaste.ewasteStore) globalEWaste.ewasteStore = [];
  globalEWaste.ewasteStore.unshift(newListing);

  if (isSupabaseConfigured()) {
    try {
      const { data: suItem, error } = await supabaseAdmin
        .from("ewaste_listings")
        .insert({
          device_name: item.deviceName,
          brand: item.brand,
          category: item.category,
          condition: item.condition,
          estimated_age: item.estimatedAge,
          description: item.description,
          image_url: item.imageUrl,
          price: item.price,
          weight_kg: item.weightKg,
          seller_name: item.sellerName,
          seller_city: item.sellerCity,
          seller_role: item.sellerRole,
          status: "AVAILABLE",
        })
        .select()
        .single();

      if (suItem && !error) {
        newListing.id = suItem.id;
      }
    } catch (e) {
      console.warn("Supabase ewaste insert error:", e);
    }
  }

  return newListing;
}

export function addEWasteListing(item: Omit<EWasteListing, "id" | "createdAt" | "status">): EWasteListing {
  const newListing: EWasteListing = {
    ...item,
    id: `ew_${Date.now()}`,
    status: "AVAILABLE",
    createdAt: new Date().toISOString(),
  };
  if (!globalEWaste.ewasteStore) globalEWaste.ewasteStore = [];
  globalEWaste.ewasteStore.unshift(newListing);
  return newListing;
}

export async function deleteEWasteListingAsync(id: string): Promise<boolean> {
  if (globalEWaste.ewasteStore) {
    globalEWaste.ewasteStore = globalEWaste.ewasteStore.filter((item) => item.id !== id);
  }
  if (isSupabaseConfigured()) {
    try {
      await supabaseAdmin.from("ewaste_listings").delete().eq("id", id);
    } catch (e) {
      console.warn("Supabase delete error:", e);
    }
  }
  return true;
}

export function deleteEWasteListing(id: string): boolean {
  if (globalEWaste.ewasteStore) {
    const initialLen = globalEWaste.ewasteStore.length;
    globalEWaste.ewasteStore = globalEWaste.ewasteStore.filter((item) => item.id !== id);
    return globalEWaste.ewasteStore.length < initialLen;
  }
  return false;
}

export function deleteEWasteListingsByKeyword(keyword: string): number {
  if (globalEWaste.ewasteStore) {
    const initialLen = globalEWaste.ewasteStore.length;
    const lower = keyword.toLowerCase();
    globalEWaste.ewasteStore = globalEWaste.ewasteStore.filter(
      (item) =>
        !item.deviceName.toLowerCase().includes(lower) &&
        !item.description.toLowerCase().includes(lower) &&
        !item.imageUrl.toLowerCase().includes(lower)
    );
    return initialLen - globalEWaste.ewasteStore.length;
  }
  return 0;
}
